service: serverless-http-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get

resources:
  - ${file(./infrastructure/sqs/queues.yml)}
