service: serverless-http-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get

resources:
  - ${file(./infrastructure/sqs/queues.yml)}
  - ${file(./infrastructure/alarms/_sqs-dlq-alarms.yml):Alarms}
  - ${file(./infrastructure/alarms/_sqs-queue-alarms.yml):Alarms}
  - ${file(./infrastructure/alarms/_api-gateway-alarms.yml):Alarms}
  - ${file(./infrastructure/alarms/_lambda-alarms.yml):Alarms}
